version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file: ./api-gateway/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis-17138.c10.us-east-1-4.ec2.redns.redis-cloud.com:17138
      - RABBITMQ_URL=amqps://kasovzdq:ns0u_NutiNNtWWZY259qcKzZekaZYdry@fuji.lmq.cloudamqp.com/kasovzdq

  identity-service:
    build: ./identity-service
    env_file: ./identity-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis-17138.c10.us-east-1-4.ec2.redns.redis-cloud.com:17138
      - RABBITMQ_URL=amqps://kasovzdq:ns0u_NutiNNtWWZY259qcKzZekaZYdry@fuji.lmq.cloudamqp.com/kasovzdq

  post-service:
    build: ./post-service
    env_file: ./post-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis-17138.c10.us-east-1-4.ec2.redns.redis-cloud.com:17138
      - RABBITMQ_URL=amqps://kasovzdq:ns0u_NutiNNtWWZY259qcKzZekaZYdry@fuji.lmq.cloudamqp.com/kasovzdq

  media-service:
    build: ./media-service
    env_file: ./media-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis-17138.c10.us-east-1-4.ec2.redns.redis-cloud.com:17138
      - RABBITMQ_URL=amqps://kasovzdq:ns0u_NutiNNtWWZY259qcKzZekaZYdry@fuji.lmq.cloudamqp.com/kasovzdq

  search-service:
    build: ./search-service
    env_file: ./search-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis-17138.c10.us-east-1-4.ec2.redns.redis-cloud.com:17138
      - RABBITMQ_URL=amqps://kasovzdq:ns0u_NutiNNtWWZY259qcKzZekaZYdry@fuji.lmq.cloudamqp.com/kasovzdq

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
